name: geezdate
description: A simple and minimalisting date utility that helps you work with ethiopian date in dart/flutter.
  እኛ ራሳችን ለራሳችን ካልሰራን ማን ይሰራልናል። ኣንድ ፈረንጅ መቶ ኣይሰራልን።

version: 0.0.10
repository: https://github.com/kidusdev/geezdate_dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  jiffy: ^6.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
