name: geezdate
version: 0.0.11

description: A simple and minimalisting date utility that helps you to work with ethiopian date in dart/flutter.

repository: https://github.com/kidusdev/geezdate_dart
issue_tracker: https://github.com/kidusdev/geezdate_dart/issues

publish_to: https://pub.dev

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.2.3

dependencies:
  jiffy: ^6.2.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

topics:
  - date
  - ethiopian_date
  - ethiopian to gregorian calender converter
  - gregorian to ethiopian calender converter
