name: geezdate
version: 0.0.12

description: A simple and minimalisting date utility that helps you to work with ethiopian date in dart/flutter.

repository: https://github.com/kidusdev/geezdate_dart
issue_tracker: https://github.com/kidusdev/geezdate_dart/issues

environment:
  sdk: ^3.2.3

dependencies:
  jiffy: ^6.2.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
